name: Build

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '18.3.0'
#          registry-url: 'https://npm.pkg.github.com'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/setup-node@v4
        with:
          node-version: '22.2.0 '
          registry-url: 'https://artifacts.itemis.cloud/repository/npm-open/'
          scope: '<@modelix>'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -PciBuild=true -Pgpr.token=${{ secrets.GITHUB_TOKEN }} -Pmps.version.major=2023.3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: kernelf-angular-demo/dist/kernelf-angular-demo
      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: |
            */build/test-results
            */build/reports

# Disabled because the repository is private and they need payment
#  # Deploy job
#  deploy:
#    # Add a dependency to the build job
#    needs: build
#
#    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
#    permissions:
#      pages: write      # to deploy to Pages
#      id-token: write   # to verify the deployment originates from an appropriate source
#
#    # Deploy to the github-pages environment
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    # Specify runner + deployment step
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
